import Script from 'next/script'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        {/* AgentStack Widget */}
        <Script id="agentstack-init" strategy="lazyOnload">
          {`window.agentstack=new Proxy({_q:[]},{get(t,p){if(p==='_q')return t._q;return(...a)=>t._q.push([p,...a]);}});`}
        </Script>
        <Script
          src="https://www.agentstack.build/embed.js"
          data-agent-id="xlb0EGyfRIce"
          strategy="lazyOnload"
        />
      </body>
    </html>
  )
}
